#! /bin/sh
. /home/mxhectorvega/.cache/wal/colors.sh
pkill -9 polybar &

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor LVDS1 -d I II III IV V
#bspc monitor HDMI3 -d VI VII VIII IX X

bspc config presel_feedback_color 	"$color2"
bspc config focused_border_color	"$color2"
bspc config directional_focus_tightness low
bspc config merge_overlapping_monitors true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config automatic_scheme longest_side
bspc config focused_frame_opacity 0.05
bspc config normal_frame_opacity 1.0
bspc config window_gap		15
bspc config border_width	0
bspc config top_padding		0
bspc config split_ratio   	0.50

bspc rule -a Pavucontrol state=tiled rectangle=600x400+0+0 center=on
bspc rule -a youtube-dl state=tiled rectangle=800x500+0+0 center=on
bspc rule -a chromium state=tiled rectangle=800x500+0+0 center=on
bspc rule -a firefox state=tiled rectangle=800x500+0+0 center=on
#bspc rule -a Pcmanfm state=tiled rectangle=800x500+0+0 center=on
bspc rule -a Surf state=tiled rectangle=800x500+0+0 center=on
bspc rule -a ytdl state=tiled rectangle=800x500+0+0 center=on
bspc rule -a Sxiv state=tiled rectangle=800x500+0+0 center=on
bspc rule -a mpv state=tiled rectangle=800x500+0+0 center=on
bspc rule -a St state=tiled rectangle=800x500+0+0 center=on
bspc rule -a XTerm state=tiled rectangle=800x500+0+0 center=on
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a libreoffice state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

export SUDO_ASKPASS="/home/mxhectorvega/.config/bspwm/scripts/menupass"
export PATH="${PATH}:/home/mxhectorvega/.config/bspwm/scripts/"
export PATH="${PATH}:/home/mxhectorvega/.config/lemonbar"
export PATH="${PATH}:/home/mxhectorvega/.config/polybar"
export PATH="${PATH}:/home/mxhectorvega/.config/bspwm/"
export BROWSER=firefox
export READER=zathura
export TERMINAL=xterm
export EDITOR=nvim

#sudo mount -t ext2fs -o ro /dev/ada0s1 /media/Backup &
#curl -sf "wttr.in/VER?format=1" > /tmp/climasimple &
#curl -sf "wttr.in/VER?lang=es" > /tmp/clima &
pgrep -x sxhkd > /dev/null || sxhkd &
#resoluciones > /tmp/resoluciones &
xsetroot -cursor_name left_ptr
xrdb -merge ~/.Xresources
#pkill -9 lemonbar &
xset r rate 300 50 &
#recargardunst &
#devilspie -a &
#demoniompc &
polybar bar &
xset b off &
unclutter &
#xcompmgr &
./.fehbg &
musicpd &
#devmon &
wal -i &
#panel &
picom &